### ISSUE TITLE
Only one audio should be played at the same time. How to do this?

### ISSUE THREAD

**Issue by gzlboy** [exyte/Chat#97]
Hi, i found that when there are multiple voice messages, you can click play at the same time. This should be unreasonable. You should click this one and pause the others.
Have a good day!

**Comment by gzlboy** [comment]
I have fixed this in PR:)

**Comment by f3dm76** [comment]
Hey @gzlboy, I merged the PR, could you please look into removing that 160? I checked out the code a bit, there is a Geometry reader there - doesn't it already return the value without the paddings and play button? Maybe the problem is smth else. In any case have a wonderful day, and thank you again for fixing so much stuff!

**Comment by gzlboy** [comment]
Hi alisa, 
I'm very sorry, I spent several days trying to solve this 160, but I still can't solve it. If you have time, please take a look. Or wait for other friends to solve it.

Have a nice day!
